import { useEffect, useMemo, useState } from "react";
import { Activity, ArrowRight, Bot, CheckCircle2, ChevronDown, Clock3, Database, FileText, LockKeyhole, MessageCircleQuestion, ScanSearch, ShieldAlert, ShieldCheck, Sparkles, Stethoscope, XCircle } from "lucide-react";
import { AnswerDetails } from "@/components/AnswerDetails";
import { AnswerSurface } from "@/components/AnswerSurface";
import { EvidencePanel } from "@/components/EvidencePanel";
import { PipelineSteps } from "@/components/PipelineSteps";
import { ProcessingSteps } from "@/components/ProcessingSteps";
import { ScopeCards } from "@/components/ScopeCards";
import { SystemStats } from "@/components/SystemStats";
import { clinicalApi } from "@/lib/api";
import type { DemoScenario, HealthResponse, MetricsResponse, QueryResponse } from "@/types/clinical";

const defaultScenarios: DemoScenario[] = [
  { id: "bp", title: "Blood pressure measurement", query: "What are the NICE recommendations for measuring blood pressure in adults?", disease: "hypertension" },
  { id: "diabetes", title: "Type 2 diabetes symptoms", query: "What are the symptoms of type 2 diabetes?", disease: "type_2_diabetes" },
  { id: "refusal", title: "Safe out-of-scope refusal", query: "What are the symptoms of asthma?", disease: "unsupported" },
];

function Signal({ label, value, live }: { label: string; value: string; live?: boolean }) {
  return <div className="rounded-xl border border-slate-200 bg-white/90 p-3 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400">{label}</p><p className="mt-1 flex items-center gap-1.5 text-sm font-semibold capitalize text-[#13213a]">{live && <span className="size-1.5 rounded-full bg-teal-500" />}{value}</p></div>;
}

function TopicBadge({ result }: { result: QueryResponse }) {
  const label = result.detected_disease === "type_2_diabetes" ? "Type 2 Diabetes" : result.detected_disease === "hypertension" ? "Hypertension" : result.detected_disease === "unsupported" ? "Outside current scope" : "Needs clarification";
  const supported = result.detected_disease === "hypertension" || result.detected_disease === "type_2_diabetes";
  return <div className={`rounded-2xl border p-5 shadow-sm ${supported ? "border-teal-100 bg-gradient-to-br from-teal-50 to-white" : "border-amber-100 bg-gradient-to-br from-amber-50 to-white"}`}><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-slate-500">Detected medical topic</p><h3 className="mt-2 font-display text-xl font-semibold text-[#13213a]">{label}</h3><p className="mt-1 text-sm text-slate-600">{supported ? "The answer is routed through the matching guideline collection." : "The assistant will not use general LLM knowledge outside the registered corpus."}</p></div>{supported ? <ShieldCheck className="size-6 text-teal-600" /> : <ShieldAlert className="size-6 text-amber-600" />}</div>{supported ? <div className="mt-5"><div className="flex items-center justify-between text-xs font-bold text-slate-500"><span>Routing confidence</span><span className="text-teal-700">{(result.classification_confidence * 100).toFixed(0)}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white ring-1 ring-teal-100"><div className="h-full rounded-full bg-gradient-to-r from-teal-500 to-blue-500 transition-all" style={{ width: `${Math.max(4, result.classification_confidence * 100)}%` }} /></div><p className="mt-2 text-[11px] text-slate-500">Classifier confidence, not medical certainty.</p></div> : <p className="mt-4 rounded-xl bg-white/80 p-3 text-sm font-medium leading-6 text-amber-800 ring-1 ring-amber-100">Currently supported: hypertension and type 2 diabetes.</p>}</div>;
}

function UnsupportedCard() {
  return <div className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><div className="flex items-start gap-3"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-white text-amber-600"><XCircle className="size-5" /></div><div><h3 className="font-display text-lg font-semibold text-amber-950">This question is outside the current knowledge base.</h3><p className="mt-2 text-sm leading-6 text-amber-800">The assistant deliberately avoids answering from general model knowledge. Try a question about one of the supported topics.</p><div className="mt-4 flex flex-wrap gap-2 text-xs font-bold text-amber-900"><span className="rounded-full bg-white px-3 py-1.5">Hypertension</span><span className="rounded-full bg-white px-3 py-1.5">Type 2 Diabetes</span></div></div></div></div>;
}

function HowItWorks() {
  return <section id="technology" className="border-y border-slate-200 bg-[#f6f9fb] px-5 py-14 sm:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-[11px] font-bold uppercase tracking-[0.16em] text-teal-700">How it works</p><h2 className="mt-2 font-display text-3xl font-semibold tracking-[-0.03em] text-[#13213a]">A transparent medical AI workflow.</h2><p className="mt-3 text-sm leading-6 text-slate-600">The interface makes the system understandable without exposing technical controls that belong in the backend.</p></div><div className="mt-8 grid gap-4 md:grid-cols-5">{[{ n: "01", title: "Question", text: "You ask naturally in English or Arabic.", icon: MessageCircleQuestion }, { n: "02", title: "Topic", text: "The system identifies the supported medical topic.", icon: Activity }, { n: "03", title: "Evidence", text: "Relevant guideline chunks are retrieved.", icon: Database }, { n: "04", title: "Verification", text: "Sources are reranked and checked.", icon: CheckCircle2 }, { n: "05", title: "Answer", text: "Only grounded, cited information is disclosed.", icon: FileText }].map((item) => { const Icon = item.icon; return <article key={item.n} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><span className="font-mono text-xs font-bold text-teal-700">{item.n}</span><Icon className="size-5 text-slate-400" /></div><h3 className="mt-8 font-display text-lg font-semibold text-[#13213a]">{item.title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{item.text}</p></article>; })}</div></div></section>;
}

export default function Home() {
  const [health, setHealth] = useState<HealthResponse | null>(null);
  const [metrics, setMetrics] = useState<MetricsResponse | null>(null);
  const [scenarios, setScenarios] = useState<DemoScenario[]>(defaultScenarios);
  const [query, setQuery] = useState("");
  const [result, setResult] = useState<QueryResponse | null>(null);
  const [showDetails, setShowDetails] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    clinicalApi.health().then(setHealth).catch(() => setHealth(null));
    clinicalApi.metrics().then(setMetrics).catch(() => setMetrics(null));
    clinicalApi.scenarios().then(setScenarios).catch(() => setScenarios(defaultScenarios));
  }, []);

  const selectedConfiguration = useMemo(() => String(metrics?.langchain?.selected_configuration || metrics?.retrieval?.selected_configuration || "Hybrid retrieval"), [metrics]);

  async function askAI() {
    if (query.trim().length < 3) { setError("Please enter a clinical question with at least three characters."); return; }
    setLoading(true); setError(null); setShowDetails(false); setResult(null);
    try { setResult(await clinicalApi.query({ query: query.trim() })); }
    catch { setError("We could not complete the request right now. Please check that the FastAPI service is running and try again."); }
    finally { setLoading(false); }
  }

  function applyScenario(item: DemoScenario) { setQuery(item.query); setResult(null); setError(null); setShowDetails(false); document.getElementById("ask")?.scrollIntoView({ behavior: "smooth", block: "center" }); }

  return <div className="min-h-screen bg-[#f4f7fa] text-[#13213a]">
    <header className="sticky top-0 z-30 border-b border-slate-200/80 bg-white/90 px-5 py-3 backdrop-blur-xl sm:px-8"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4"><a href="#top" className="flex items-center gap-3" aria-label="NICE Clinical Evidence home"><div className="relative grid size-9 place-items-center overflow-hidden rounded-lg bg-[#13213a] text-sm font-black text-teal-200">N<span className="absolute bottom-1 right-1 size-1.5 rounded-full bg-teal-300" /></div><div><p className="font-display text-sm font-bold tracking-tight">NICE Clinical</p><p className="text-[9px] font-bold uppercase tracking-[0.16em] text-teal-700">Evidence AI</p></div></a><nav className="hidden items-center gap-6 text-xs font-semibold text-slate-500 md:flex"><a href="#technology" className="transition hover:text-teal-700">How it works</a><a href="#scope" className="transition hover:text-teal-700">Medical scope</a><a href="#evaluation" className="transition hover:text-teal-700">Evaluation</a></nav><div className="flex items-center gap-2"><span className="hidden rounded-full bg-emerald-50 px-3 py-1.5 text-[11px] font-bold text-emerald-700 sm:inline-flex"><span className="mr-1.5 size-1.5 rounded-full bg-emerald-500" />{health?.status === "ok" ? "System ready" : "Checking system"}</span><a href="#ask" className="rounded-lg bg-[#13213a] px-3.5 py-2 text-xs font-bold text-white transition hover:bg-[#1c3151]">Ask AI</a></div></div></header>

    <main id="top">
      <section className="relative overflow-hidden bg-[#101c33] px-5 py-12 sm:px-8 sm:py-16"><div className="absolute -right-24 -top-24 size-96 rounded-full bg-teal-400/20 blur-3xl" /><div className="absolute bottom-0 right-1/4 size-72 rounded-full bg-blue-500/15 blur-3xl" /><div className="absolute inset-0 bg-gradient-to-r from-[#101c33] via-[#101c33]/95 to-[#101c33]/35" /><div className="relative mx-auto max-w-7xl"><div className="max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full border border-teal-200/25 bg-teal-300/10 px-3 py-1.5 text-[11px] font-bold uppercase tracking-[0.14em] text-teal-100"><Sparkles className="size-3.5" /> Evidence-grounded medical AI</div><h1 className="mt-5 font-display text-4xl font-semibold leading-[1.08] tracking-[-0.05em] text-white sm:text-6xl">Ask a medical question.<br /><span className="text-teal-300">See the evidence.</span></h1><p className="mt-5 max-w-2xl text-base leading-7 text-slate-300 sm:text-lg">A focused AI assistant for educational information from NICE guidance on hypertension and type 2 diabetes — with transparent retrieval, citations, and safety boundaries.</p><div className="mt-7 flex flex-wrap gap-3"><a href="#ask" className="inline-flex items-center gap-2 rounded-xl bg-teal-500 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-teal-950/30 transition hover:bg-teal-400">Ask a medical question <ArrowRight className="size-4" /></a><a href="#technology" className="inline-flex items-center gap-2 rounded-xl border border-white/15 bg-white/5 px-5 py-3 text-sm font-semibold text-slate-200 transition hover:bg-white/10">Explore the workflow</a></div></div><div className="mt-10"><PipelineSteps /></div></div></section>

      <section id="ask" className="scroll-mt-24 px-5 py-10 sm:px-8 sm:py-14"><div className="mx-auto max-w-7xl"><div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_330px]"><div className="space-y-6"><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-[0_18px_55px_rgba(15,32,58,0.08)] sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[0.16em] text-teal-700"><Bot className="size-4" /> Medical AI workspace</div><h2 className="mt-2 font-display text-2xl font-semibold tracking-[-0.03em]">What would you like to understand?</h2><p className="mt-2 text-sm leading-6 text-slate-500">Ask naturally. The system handles topic identification and evidence retrieval for you.</p></div><span className="inline-flex items-center gap-1.5 rounded-full bg-slate-100 px-3 py-1.5 text-[10px] font-bold text-slate-500"><LockKeyhole className="size-3" /> No technical controls</span></div><label htmlFor="clinical-question" className="sr-only">Ask your medical question</label><textarea id="clinical-question" value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => { if ((event.metaKey || event.ctrlKey) && event.key === "Enter") askAI(); }} className="mt-6 min-h-36 w-full resize-y rounded-2xl border border-slate-200 bg-slate-50/70 p-4 text-[15px] leading-7 outline-none transition placeholder:text-slate-400 focus:border-teal-500 focus:bg-white focus:ring-4 focus:ring-teal-50" placeholder="Ask your medical question... e.g. What are the symptoms of type 2 diabetes?" /><div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-slate-400">English, Arabic, and natural phrasing supported.</p><div className="flex gap-2"><button type="button" onClick={() => { setQuery(""); setResult(null); setError(null); setShowDetails(false); }} className="rounded-xl border border-slate-200 px-4 py-3 text-sm font-semibold text-slate-600 transition hover:bg-slate-50">Clear</button><button type="button" onClick={askAI} disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-xl bg-teal-600 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-teal-600/20 transition hover:bg-teal-700 disabled:cursor-not-allowed disabled:opacity-60">{loading ? <Clock3 className="size-4 animate-spin" /> : <Sparkles className="size-4" />}{loading ? "Processing..." : "Ask AI"}</button></div></div></section>{(loading || result) && <ProcessingSteps active={loading} />}{error && <div role="alert" className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm leading-6 text-rose-700"><div className="flex gap-2"><ShieldAlert className="mt-0.5 size-4 shrink-0" /><p>{error}</p></div></div>}{result && <><TopicBadge result={result} />{result.detected_disease === "unsupported" || result.detected_disease === "ambiguous" ? <UnsupportedCard /> : <>
                <AnswerSurface result={result} />
                {result.safety_status !== "REFUSED" && (
                  <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
                    <button type="button" onClick={() => setShowDetails((value) => !value)} className="flex w-full items-center justify-between gap-3 px-5 py-4 text-left">
                      <span className="flex items-center gap-2 text-sm font-bold text-[#13213a]"><ScanSearch className="size-4 text-teal-700" /> {showDetails ? "Hide" : "View"} sources &amp; evidence details</span>
                      <span className="flex items-center gap-2"><span className="rounded-full bg-teal-50 px-2.5 py-1 text-[11px] font-bold text-teal-700">{result.retrieved_chunks.length} chunks</span><ChevronDown className={`size-4 shrink-0 text-slate-400 transition-transform ${showDetails ? "rotate-180" : ""}`} /></span>
                    </button>
                    {showDetails && (
                      <div className="space-y-6 border-t border-slate-100 px-5 py-5">
                        <EvidencePanel chunks={result.retrieved_chunks} isLoading={false} />
                        <AnswerDetails result={result} />
                      </div>
                    )}
                  </section>
                )}
              </>}</>}</div><aside className="space-y-4"><section className="rounded-3xl bg-[#13213a] p-6 text-white shadow-xl shadow-slate-900/10"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-teal-300">Built for trustworthy review</p><h2 className="mt-3 font-display text-xl font-semibold">Evidence first, answer second.</h2><p className="mt-3 text-sm leading-6 text-slate-300">Every supported answer stays connected to the retrieved guideline chunks, page ranges, and recommendation identifiers.</p><div className="mt-6 space-y-3 text-sm"><div className="flex gap-3"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-teal-300" /><span className="text-slate-200">Source traceability built into the response.</span></div><div className="flex gap-3"><ShieldCheck className="mt-0.5 size-4 shrink-0 text-teal-300" /><span className="text-slate-200">Out-of-scope and unsafe questions are refused deliberately.</span></div><div className="flex gap-3"><FileText className="mt-0.5 size-4 shrink-0 text-teal-300" /><span className="text-slate-200">Medical information is educational, not a diagnosis.</span></div></div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><MessageCircleQuestion className="size-4 text-teal-700" /><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-slate-500">Try a demo question</p></div><div className="mt-3 space-y-2">{scenarios.map((item) => <button type="button" key={item.id} onClick={() => applyScenario(item)} className="group flex w-full items-center justify-between rounded-xl border border-slate-200 p-3 text-left transition hover:border-teal-200 hover:bg-teal-50"><span><span className="block text-sm font-semibold text-[#13213a]">{item.title}</span><span className="mt-1 block line-clamp-2 text-xs leading-5 text-slate-500">{item.query}</span></span><ArrowRight className="ml-3 size-4 shrink-0 text-slate-400 transition group-hover:translate-x-1 group-hover:text-teal-600" /></button>)}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">Live system</p><div className="mt-3 space-y-2"><Signal label="Vector store" value={health?.vector_store || "Checking"} live={Boolean(health)} /><Signal label="LLM provider" value={health ? `${health.llm_provider} · ${health.llm_available ? "available" : "fallback"}` : "Checking"} /><Signal label="Indexed chunks" value={health ? String(health.indexed_chunks) : "—"} /></div></section></aside></div></div></section>

      <ScopeCards />
      <HowItWorks />
      <section id="evaluation" className="relative overflow-hidden border-b border-slate-200 bg-white px-5 py-14 sm:px-8"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(20,184,166,0.10),transparent_34%),radial-gradient(circle_at_bottom_left,rgba(59,130,246,0.07),transparent_30%)]" /><div className="relative mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[11px] font-bold uppercase tracking-[0.16em] text-teal-700">Measured evaluation</p><h2 className="mt-2 font-display text-3xl font-semibold tracking-[-0.03em]">A review record, not a marketing claim.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">The project keeps retrieval and safety metrics visible for technical review. Values are shown only when returned by the backend evaluation artifacts.</p></div><span className="rounded-full border border-slate-200 bg-white/90 px-3 py-1.5 text-xs font-semibold text-slate-600">Selected: {selectedConfiguration}</span></div><div className="mt-8"><SystemStats health={health} /></div></div></section>
      <section className="px-5 py-8 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 text-xs text-slate-500 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-2"><Stethoscope className="mt-0.5 size-4 shrink-0 text-teal-700" /><p><span className="font-bold text-slate-700">Medical information notice:</span> This AI provides educational information based on the available knowledge base. It does not replace professional medical advice, diagnosis, or treatment.</p></div><span className="shrink-0 font-semibold text-slate-400">NICE NG28 + NG136</span></div></section>
    </main>
    <footer className="border-t border-slate-200 bg-white px-5 py-7 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-3 text-xs text-slate-500 sm:flex-row sm:items-center sm:justify-between"><span>© NICE Clinical Evidence AI · Evidence-grounded prototype</span><span className="flex items-center gap-1.5"><ShieldCheck className="size-3.5 text-teal-600" /> Designed for safe educational review</span></div></footer>
  </div>;
}
