import { Activity, Droplets, HeartPulse, ShieldCheck } from "lucide-react";

const topics = [
  { title: "Hypertension", arabic: "ارتفاع ضغط الدم", description: "Blood pressure, risk factors, monitoring, lifestyle, and guideline-based management.", icon: HeartPulse, accent: "from-blue-50 to-white", iconStyle: "bg-blue-100 text-blue-700" },
  { title: "Type 2 Diabetes", arabic: "السكري من النوع الثاني", description: "Glucose management, HbA1c, lifestyle, medicines, and related NICE guidance.", icon: Droplets, accent: "from-teal-50 to-white", iconStyle: "bg-teal-100 text-teal-700" },
];

export function ScopeCards() {
  return <section id="scope" className="border-y border-slate-200 bg-white px-5 py-12 sm:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-[11px] font-bold uppercase tracking-[0.16em] text-teal-700">Supported medical topics</p><h2 className="mt-2 font-display text-3xl font-semibold tracking-[-0.03em] text-[#13213a]">Focused knowledge. Safer answers.</h2><p className="mt-3 text-sm leading-6 text-slate-600">The assistant is intentionally scoped to two adult NICE guideline collections. Questions outside this scope are handled as a deliberate safe refusal.</p></div><div className="mt-7 grid gap-4 md:grid-cols-2">{topics.map((topic) => { const Icon = topic.icon; return <article key={topic.title} className={`rounded-2xl border border-slate-200 bg-gradient-to-br ${topic.accent} p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md`}><div className="flex items-start justify-between"><div className={`grid size-11 place-items-center rounded-xl ${topic.iconStyle}`}><Icon className="size-5" /></div><span className="inline-flex items-center gap-1 rounded-full bg-white px-2.5 py-1 text-[10px] font-bold text-emerald-700 ring-1 ring-slate-200"><ShieldCheck className="size-3" /> Evidence scope</span></div><h3 className="mt-6 font-display text-xl font-semibold text-[#13213a]">{topic.title}</h3><p className="mt-1 text-xs font-semibold text-teal-700">{topic.arabic}</p><p className="mt-3 max-w-md text-sm leading-6 text-slate-600">{topic.description}</p><div className="mt-5 flex items-center gap-2 text-xs font-semibold text-slate-500"><Activity className="size-4 text-teal-600" /> Source-grounded educational information</div></article>; })}</div></div></section>;
}
